# Dave is the first robot to be deployed
# Dave was demoed on:
# And in production on: 

name: Dave
motor_arduino: /dev/cu.usbmodem1401
suction_cup_arduino: /dev/cu.usbserial-110

sort_containers: ["plastic", "metal", "metal-can", "plastic-can", "paper"] 
sleep_position: [0, 0]
ready_position: [0, 0]
plastic_position: [0, 0]
plastic_cans_position: [0, 0]
metal_position: [0, 0]
metal_cans_position: [0, 0]
paper_position: [20, 5]

max_x: 1000
max_y: 1000

xy_max_speed: 2000
xy_acceleration: 1000
xy_steps_per_rev: 800

z_max_speed: 1000
z_acceleration: 500
z_steps_per_rev: 800

conveyor_speed: 8.727 # cm/s
cms_for_10_revolutions: 60
